TrajectoryPlannerROS:
		max_vel_x:	0.2
		min_vel_x:	0.05
		max_rotational_vel:	0.15
		min_in_place_rotational_vel:	0.01
		min_in_place_vel_theta:	0.01
		max_vel_theta:	0.15
		min_vel_theta:	-0.15
		acc_lim_th:	3.2
		acc_lim_x:	2.5 # aceleration limit in x direction meters/sec^2
		acc_lim_y:	2.5
		holonomic_robot: false


TrajectoryPlannerROS:
    acc_lim_x: 0.025 #
    acc_lim_theta: 0.01
    max_vel_x: 0.20
    min_vel_x: 0.01
    max_rotational_vel: 0.2
    min_in_place_rotational_vel: 0.18182
    holonomic_robot: false
    xy_goal_tolerance: 0.250
    yaw_goal_tolerance: 0.20
    sim_granularity: 0.025
    vx_samples: 10
    vtheta_samples: 20
    goal_distance_bias: 10
    path_distance_bias: 22
    occdist_scale: 0.01
    heading_lookahead: 0.325
    oscillation_reset_dist: 0.08


controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.15
  min_vel_x: 0.01
  max_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.03
  acc_lim_theta: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  holonomic_robot: false
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.1
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 1.5
  heading_lookahead: 0.325
  meter_scoring: true
  vx_samples: 6
  vtheta_samples: 20
  dwa: false