controller_frequency: 5.0
TrajectoryPlannerROS:
		max_vel_x:	0.2 #maximum forward velocity allowed for the base in meters/sec
		min_vel_x:	0.05 #minimum forward velocity allowed for the base in meters/sec
		                 #(used to overcome friction)
		#max_rotational_vel:	0.15
		max_vel_theta:	0.15
		min_vel_theta:	-0.15
		min_in_place_rotational_vel: 0.05 #min in-place rotational velocity in rad/sec

		#acc_lim_th:	3.2
		acc_lim_theta: 0.1 #rotational acceleration limit of the robot in radians/sec^2
		acc_lim_x:	1.0 # aceleration limit in x direction meters/sec^2
		acc_lim_y:	1.0 # aceleration limit in y direction meters/sec^2
		xy_goal_tolerance: 0.250
		yaw_goal_tolerance: 0.20
        sim_granularity: 0.025
        vx_samples: 10
        vtheta_samples: 20
        goal_distance_bias: 10
        path_distance_bias: 22
        occdist_scale: 0.01
        heading_lookahead: 0.325
        oscillation_reset_dist: 0.08
        sim_time: 1.5
		holonomic_robot: false
		meter_scoring: true
		escape_vel: -0.15
		dwa: false