global_costmap:
		#The global_frame and the robot_base_frame 	attributes	define	the	transformation	between	the map	and	the	robot.
		global_frame:	/map #sets the global frame
		robot_base_frame:	base_footprint #frame of the robot
		update_frequency:	1.0 #freqency of the map update in Hz
		publish_frequency: 1 # rate, in Hz, at which the costmap will publish visualization information
		static_map: true # whether or not the costmap should initialize itself based on a map served by the map_server

        # other possible options
        # origin_x: -10
        # origin_y: -10
        # width: 20.0
        # height: 20.0
        # resolution: 0.1


