local_costmap:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 1.5
      static_map: false
      rolling_window: true
      width: 8.0
      height: 8.0
      resolution: 0.05
      transform_tolerance: 0.15
      planner_frequency: 5.0
      planner_patiente: 1.0