local_costmap:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 2.5
      static_map: false
      rolling_window: true
      width: 8.0
      height: 8.0
      resolution: 0.025
      transform_tolerance: 0.15
      planner_frequency: 5.0
      planner_patiente: 1.0